version: "3"

services:
  platform:
    image: resource-catalogue-ui                         # edit image name

    environment:
    - PLATFORM_API_ENDPOINT=http://example.com  # edit api endpoint
    - FAQ_API_ENDPOINT=http://example.com       # edit faq endpoint
    - MATOMO_HOST=http://example.com/matomo     # edit matomo host
    - MATOMO_SITE_ID=1                          # edit matomo site id

    ports:
    - "80:80"

    networks:
    - eic-net

    volumes:
      - <my/images/dir>:/images

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20

networks:
  eic-net:
    external: true
